version: "3.1"
services:
  apache-php:
    container_name: apache-php
    build:
      context: ./apache-php
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - mysql
    networks:
      - default

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: tecsup123
        MYSQL_DATABASE: credenciales_db
        MYSQL_USER: administrador
        MYSQL_PASSWORD: tecsup123
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mysql:mysql
    ports:
      - 8000:80
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: tecsup123
        MYSQL_ROOT_PASSWORD: tecsup123 

volumes:
    persistent: